# Generated by Django 3.1.14 on 2022-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок курса')),
                ('language', models.CharField(max_length=50, verbose_name='Язык программирования')),
                ('direction', models.CharField(max_length=100, verbose_name='Направление курса')),
                ('certification', models.CharField(max_length=250, verbose_name='Информация об сертификате')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('price', models.IntegerField(verbose_name='Стоимость курса')),
                ('hours', models.IntegerField(verbose_name='Сколько часов курс займёт')),
                ('lections', models.IntegerField(verbose_name='Количество лекций в курсе')),
                ('skill', models.CharField(max_length=50, verbose_name='Необходимый уровень знаний')),
                ('when_start', models.DateTimeField(verbose_name='Начало курса')),
                ('when_end', models.DateTimeField(verbose_name='Конец курса')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('Avatar', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
                ('courses', models.ManyToManyField(related_name='students', to='main.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
