# Generated by Django 3.1.14 on 2022-10-22 20:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('course', models.ManyToManyField(related_name='requests', to='main.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
