# Generated by Django 3.1.14 on 2022-10-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221022_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='course',
        ),
        migrations.AddField(
            model_name='request',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.course'),
            preserve_default=False,
        ),
    ]
