# Generated by Django 3.1.14 on 2022-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221023_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='when_end',
            field=models.CharField(max_length=50, verbose_name='Конец курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='when_start',
            field=models.CharField(max_length=50, verbose_name='Начало курса'),
        ),
    ]
