# Generated by Django 3.1.14 on 2022-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221026_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='when_start',
        ),
        migrations.AddField(
            model_name='course',
            name='start_month',
            field=models.CharField(choices=[('січень', 'січень'), ('лютий', 'лютий'), ('березень', 'березень'), ('квітень', 'квітень'), ('травень', 'травень'), ('червень', 'червень'), ('липня', 'липня'), ('серпень', 'серпеь'), ('вересень', 'вересень'), ('жовтень', 'жовтень'), ('листопад', 'листопад'), ('грудень', 'грудень')], default=None, max_length=10, verbose_name='Начало курса'),
            preserve_default=False,
        ),
    ]
