# Generated by Django 3.1.14 on 2022-10-27 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221027_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='when_end',
        ),
        migrations.AddField(
            model_name='course',
            name='end_day',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='День начала курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_month',
            field=models.CharField(choices=[('січня', 'січня'), ('лютого', 'лютого'), ('березня', 'березня'), ('квітня', 'квітня'), ('травня', 'травня'), ('червня', 'червня'), ('липня', 'липня'), ('серпня', 'серпня'), ('вересня', 'вересня'), ('жовтня', 'жовтня'), ('листопада', 'листопада'), ('грудня', 'грудня')], default=None, max_length=10, verbose_name='Конец курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_day',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='День начала курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='start_month',
            field=models.CharField(choices=[('січня', 'січня'), ('лютого', 'лютого'), ('березня', 'березня'), ('квітня', 'квітня'), ('травня', 'травня'), ('червня', 'червня'), ('липня', 'липня'), ('серпня', 'серпня'), ('вересня', 'вересня'), ('жовтня', 'жовтня'), ('листопада', 'листопада'), ('грудня', 'грудня')], max_length=10, verbose_name='Месяц начала курса'),
        ),
    ]
