# Generated by Django 3.1.14 on 2022-10-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.CharField(blank=True, choices=[('9:00-11:00', '9:00-11:00'), ('11:00-13:00', '11:00-13:00'), ('13:00-15:00', '13:00-15:00'), ('15:00-17:00', '15:00-17:00'), ('17:00-19:00', '17:00-19:00'), ('19:00-21:00', '19:00-21:00')], max_length=15, null=True),
        ),
    ]
